# Generated by Django 5.1.3 on 2024-11-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeDetails',
            new_name='ResumeDetail',
        ),
    ]
